project:
  type: website
  output-dir: docs

website:
  title: "AP Pittman"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

