---
title: "On Writing A Dissertation (or, On Cooking A Steak)"
description: "A dissertation is like a steak. Maybe."
author: "AP Pittman"
date: "Mar. 9, 2026"
reference-location: margin
---

Dissertation writing – what is there to say about it besides the obvious? It’s writing. A dissertation. Long by definition: “an extended, usually written, treatment of a subject,” according to our friends Merriam and Webster. Extended – stretched or lengthened, yes; but also extended – derivative or secondary. Sort of like how after I defend this, I’ll be a doctor only in the extended sense of the word. “Treatment” is an interesting word choice, here, as well. The connotations imply making something better, like a medicine, or at the very least different, like a varnish or stain. (I think that’s a lofty goal for a 27-year-old when the “subject” in question is sociopolitical differences, and the myriad ways in which they trickle down to impact the wellbeing of everyday people. However, that's somewhat beside the point.) Right now, in year five of my Ph.D. program, I’m struggling with finishing my dissertation, the derivative varnish that will supply me with a doctorate. If you’ll indulge me in an extended metaphor…

I like most the meat and bones of research – what I think of as the butcher’s work, taking a carcass, bleeding it of the unnecessary fluids, cleaning it and sectioning it into marketable chunks. Revealing the filet mignon that lies hidden under the bloody fur of the cow. I even enjoy the cooking part of it, at least to some extent – making the slabs of raw meat fit for human consumption through the careful application of heat. But what I can’t stand – and what my task is now – is the *plating*. Nudging the finished product this way and that, adding garnish that is *completely meaningless* except for the marginal aesthetic value it provides, having to be concerned with the accoutrements of status to *signal* that the steak is good, when if you would just *eat it*, you would *know* that it’s good. And it *is* good – cooked enough for anyone to eat it safely, but raw enough to still evoke a sense of the bovine it came from. I hate having to add embellishments to the dish – they’re superfluous, pretentious, and intended to cater to the whims of a customer whose opinions on my food I truly don’t care about – or, at least, don’t *want* to care about.

But that’s the gig – an entry-level tenure-track professor is a kind of butcher-line cook-head chef hybrid, and I can’t get away with ignoring that last step. The customer I dislike is, perhaps, a food critic, and can make or break my career. And, of course, if I ignore its pleas for mercy and drag this metaphor even further down the road, I know, in a reluctant corner of my brain, that “we eat with our eyes first,” that it doesn’t matter if I have the best steak in the world: if I want someone other than my family and friends to eat it, it has to look the part. I know that a carefully prepared chimichurri can act as visual interest *and* accentuate the flavor of a steak. But I’m not as good at making chimichurri as I am at making steak. So, maybe, I’m worried that my halfhearted, fumbling attempts at plating will *ruin* my dish. And I care about my dish, so I don’t want that to happen. I want people to eat it, and I want to be able to get a job as a butcher-line cook-head chef. But I’m not sure I have the energy right now to perfect my chimichurri recipe when the world is burning down, and the steak tastes pretty damn good by itself, anyway.

I’ll leave you with my foolproof date night steak recipe[^1]: leave a cast iron skillet in the oven as you preheat it to 475 degrees. Once it’s preheated, take the skillet out and put it on a burner, high heat. Use an oil with a high smoke point, or butter if you’re brave and your girlfriend isn’t lactose intolerant. Sear both sides of a steak you’ve coated liberally with salt, and the fat cap, too, if you enjoy keeping it on – a couple of minutes per side. Then put the whole thing back in the oven until the internal temperature aligns with the results of your own personal risk-benefit calculation, probably around five minutes. Voila. Now you just have to plate it. Good luck with that.

[^1]: This part isn't a metaphor; don't hurt yourself trying to imagine what "475 degrees" means in the context of writing a dissertation.
